/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiRouteImport } from './routes/ui'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as GroupsGroupIdMembersRouteImport } from './routes/groups.$groupId_.members'
import { Route as GroupsGroupIdNotificationsRouteImport } from './routes/groups.$groupId_.notifications'
import { Route as GroupsGroupIdSettingsRouteImport } from './routes/groups.$groupId_.settings'
import { Route as GroupsGroupIdMembersUserIdRouteImport } from './routes/groups.$groupId_.members_.$userId'
import { Route as GroupsGroupIdPostsPostIdRouteImport } from './routes/groups.$groupId_.posts.$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdMembersRoute = GroupsGroupIdMembersRouteImport.update({
  id: '/groups/$groupId_/members',
  path: '/groups/$groupId/members',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdNotificationsRoute =
  GroupsGroupIdNotificationsRouteImport.update({
    id: '/groups/$groupId_/notifications',
    path: '/groups/$groupId/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdSettingsRoute = GroupsGroupIdSettingsRouteImport.update({
  id: '/groups/$groupId_/settings',
  path: '/groups/$groupId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdMembersUserIdRoute =
  GroupsGroupIdMembersUserIdRouteImport.update({
    id: '/groups/$groupId_/members_/$userId',
    path: '/groups/$groupId/members/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdPostsPostIdRoute =
  GroupsGroupIdPostsPostIdRouteImport.update({
    id: '/groups/$groupId_/posts/$postId',
    path: '/groups/$groupId/posts/$postId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ui': typeof UiRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId/notifications': typeof GroupsGroupIdNotificationsRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsRoute
  '/groups/$groupId/members/$userId': typeof GroupsGroupIdMembersUserIdRoute
  '/groups/$groupId/posts/$postId': typeof GroupsGroupIdPostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ui': typeof UiRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId/notifications': typeof GroupsGroupIdNotificationsRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsRoute
  '/groups/$groupId/members/$userId': typeof GroupsGroupIdMembersUserIdRoute
  '/groups/$groupId/posts/$postId': typeof GroupsGroupIdPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ui': typeof UiRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/groups/$groupId_/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId_/notifications': typeof GroupsGroupIdNotificationsRoute
  '/groups/$groupId_/settings': typeof GroupsGroupIdSettingsRoute
  '/groups/$groupId_/members_/$userId': typeof GroupsGroupIdMembersUserIdRoute
  '/groups/$groupId_/posts/$postId': typeof GroupsGroupIdPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ui'
    | '/groups/$groupId'
    | '/invite/$token'
    | '/groups/$groupId/members'
    | '/groups/$groupId/notifications'
    | '/groups/$groupId/settings'
    | '/groups/$groupId/members/$userId'
    | '/groups/$groupId/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ui'
    | '/groups/$groupId'
    | '/invite/$token'
    | '/groups/$groupId/members'
    | '/groups/$groupId/notifications'
    | '/groups/$groupId/settings'
    | '/groups/$groupId/members/$userId'
    | '/groups/$groupId/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/ui'
    | '/groups/$groupId'
    | '/invite/$token'
    | '/groups/$groupId_/members'
    | '/groups/$groupId_/notifications'
    | '/groups/$groupId_/settings'
    | '/groups/$groupId_/members_/$userId'
    | '/groups/$groupId_/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UiRoute: typeof UiRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  GroupsGroupIdMembersRoute: typeof GroupsGroupIdMembersRoute
  GroupsGroupIdNotificationsRoute: typeof GroupsGroupIdNotificationsRoute
  GroupsGroupIdSettingsRoute: typeof GroupsGroupIdSettingsRoute
  GroupsGroupIdMembersUserIdRoute: typeof GroupsGroupIdMembersUserIdRoute
  GroupsGroupIdPostsPostIdRoute: typeof GroupsGroupIdPostsPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/members': {
      id: '/groups/$groupId_/members'
      path: '/groups/$groupId/members'
      fullPath: '/groups/$groupId/members'
      preLoaderRoute: typeof GroupsGroupIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/notifications': {
      id: '/groups/$groupId_/notifications'
      path: '/groups/$groupId/notifications'
      fullPath: '/groups/$groupId/notifications'
      preLoaderRoute: typeof GroupsGroupIdNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/settings': {
      id: '/groups/$groupId_/settings'
      path: '/groups/$groupId/settings'
      fullPath: '/groups/$groupId/settings'
      preLoaderRoute: typeof GroupsGroupIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/members_/$userId': {
      id: '/groups/$groupId_/members_/$userId'
      path: '/groups/$groupId/members/$userId'
      fullPath: '/groups/$groupId/members/$userId'
      preLoaderRoute: typeof GroupsGroupIdMembersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/posts/$postId': {
      id: '/groups/$groupId_/posts/$postId'
      path: '/groups/$groupId/posts/$postId'
      fullPath: '/groups/$groupId/posts/$postId'
      preLoaderRoute: typeof GroupsGroupIdPostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UiRoute: UiRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  GroupsGroupIdMembersRoute: GroupsGroupIdMembersRoute,
  GroupsGroupIdNotificationsRoute: GroupsGroupIdNotificationsRoute,
  GroupsGroupIdSettingsRoute: GroupsGroupIdSettingsRoute,
  GroupsGroupIdMembersUserIdRoute: GroupsGroupIdMembersUserIdRoute,
  GroupsGroupIdPostsPostIdRoute: GroupsGroupIdPostsPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
