/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiRouteImport } from './routes/ui'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as OverviewLessonSlugRouteImport } from './routes/overview.$lessonSlug'
import { Route as GroupsGroupIdCoursesRouteImport } from './routes/groups.$groupId_.courses'
import { Route as GroupsGroupIdMembersRouteImport } from './routes/groups.$groupId_.members'
import { Route as GroupsGroupIdNotificationsRouteImport } from './routes/groups.$groupId_.notifications'
import { Route as GroupsGroupIdWordsRouteImport } from './routes/groups.$groupId_.words'
import { Route as GroupsGroupIdCoursesCourseIdRouteImport } from './routes/groups.$groupId_.courses_.$courseId'
import { Route as GroupsGroupIdMembersUserIdRouteImport } from './routes/groups.$groupId_.members_.$userId'
import { Route as GroupsGroupIdPostsPostIdRouteImport } from './routes/groups.$groupId_.posts.$postId'
import { Route as GroupsGroupIdSettingsIndexRouteImport } from './routes/groups.$groupId_.settings.index'
import { Route as GroupsGroupIdSettingsAccountRouteImport } from './routes/groups.$groupId_.settings.account'
import { Route as GroupsGroupIdSettingsGroupRouteImport } from './routes/groups.$groupId_.settings.group'
import { Route as GroupsGroupIdSettingsMembersRouteImport } from './routes/groups.$groupId_.settings.members'
import { Route as GroupsGroupIdCoursesCourseIdLessonsLessonIdRouteImport } from './routes/groups.$groupId_.courses_.$courseId_.lessons.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewLessonSlugRoute = OverviewLessonSlugRouteImport.update({
  id: '/overview/$lessonSlug',
  path: '/overview/$lessonSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdCoursesRoute = GroupsGroupIdCoursesRouteImport.update({
  id: '/groups/$groupId_/courses',
  path: '/groups/$groupId/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdMembersRoute = GroupsGroupIdMembersRouteImport.update({
  id: '/groups/$groupId_/members',
  path: '/groups/$groupId/members',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdNotificationsRoute =
  GroupsGroupIdNotificationsRouteImport.update({
    id: '/groups/$groupId_/notifications',
    path: '/groups/$groupId/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdWordsRoute = GroupsGroupIdWordsRouteImport.update({
  id: '/groups/$groupId_/words',
  path: '/groups/$groupId/words',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdCoursesCourseIdRoute =
  GroupsGroupIdCoursesCourseIdRouteImport.update({
    id: '/groups/$groupId_/courses_/$courseId',
    path: '/groups/$groupId/courses/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdMembersUserIdRoute =
  GroupsGroupIdMembersUserIdRouteImport.update({
    id: '/groups/$groupId_/members_/$userId',
    path: '/groups/$groupId/members/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdPostsPostIdRoute =
  GroupsGroupIdPostsPostIdRouteImport.update({
    id: '/groups/$groupId_/posts/$postId',
    path: '/groups/$groupId/posts/$postId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdSettingsIndexRoute =
  GroupsGroupIdSettingsIndexRouteImport.update({
    id: '/groups/$groupId_/settings/',
    path: '/groups/$groupId/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdSettingsAccountRoute =
  GroupsGroupIdSettingsAccountRouteImport.update({
    id: '/groups/$groupId_/settings/account',
    path: '/groups/$groupId/settings/account',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdSettingsGroupRoute =
  GroupsGroupIdSettingsGroupRouteImport.update({
    id: '/groups/$groupId_/settings/group',
    path: '/groups/$groupId/settings/group',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdSettingsMembersRoute =
  GroupsGroupIdSettingsMembersRouteImport.update({
    id: '/groups/$groupId_/settings/members',
    path: '/groups/$groupId/settings/members',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdCoursesCourseIdLessonsLessonIdRoute =
  GroupsGroupIdCoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/groups/$groupId_/courses_/$courseId_/lessons/$lessonId',
    path: '/groups/$groupId/courses/$courseId/lessons/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ui': typeof UiRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/overview/$lessonSlug': typeof OverviewLessonSlugRoute
  '/groups/$groupId/courses': typeof GroupsGroupIdCoursesRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId/notifications': typeof GroupsGroupIdNotificationsRoute
  '/groups/$groupId/words': typeof GroupsGroupIdWordsRoute
  '/groups/$groupId/courses/$courseId': typeof GroupsGroupIdCoursesCourseIdRoute
  '/groups/$groupId/members/$userId': typeof GroupsGroupIdMembersUserIdRoute
  '/groups/$groupId/posts/$postId': typeof GroupsGroupIdPostsPostIdRoute
  '/groups/$groupId/settings/account': typeof GroupsGroupIdSettingsAccountRoute
  '/groups/$groupId/settings/group': typeof GroupsGroupIdSettingsGroupRoute
  '/groups/$groupId/settings/members': typeof GroupsGroupIdSettingsMembersRoute
  '/groups/$groupId/settings/': typeof GroupsGroupIdSettingsIndexRoute
  '/groups/$groupId/courses/$courseId/lessons/$lessonId': typeof GroupsGroupIdCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ui': typeof UiRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/overview/$lessonSlug': typeof OverviewLessonSlugRoute
  '/groups/$groupId/courses': typeof GroupsGroupIdCoursesRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId/notifications': typeof GroupsGroupIdNotificationsRoute
  '/groups/$groupId/words': typeof GroupsGroupIdWordsRoute
  '/groups/$groupId/courses/$courseId': typeof GroupsGroupIdCoursesCourseIdRoute
  '/groups/$groupId/members/$userId': typeof GroupsGroupIdMembersUserIdRoute
  '/groups/$groupId/posts/$postId': typeof GroupsGroupIdPostsPostIdRoute
  '/groups/$groupId/settings/account': typeof GroupsGroupIdSettingsAccountRoute
  '/groups/$groupId/settings/group': typeof GroupsGroupIdSettingsGroupRoute
  '/groups/$groupId/settings/members': typeof GroupsGroupIdSettingsMembersRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsIndexRoute
  '/groups/$groupId/courses/$courseId/lessons/$lessonId': typeof GroupsGroupIdCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ui': typeof UiRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/overview/$lessonSlug': typeof OverviewLessonSlugRoute
  '/groups/$groupId_/courses': typeof GroupsGroupIdCoursesRoute
  '/groups/$groupId_/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId_/notifications': typeof GroupsGroupIdNotificationsRoute
  '/groups/$groupId_/words': typeof GroupsGroupIdWordsRoute
  '/groups/$groupId_/courses_/$courseId': typeof GroupsGroupIdCoursesCourseIdRoute
  '/groups/$groupId_/members_/$userId': typeof GroupsGroupIdMembersUserIdRoute
  '/groups/$groupId_/posts/$postId': typeof GroupsGroupIdPostsPostIdRoute
  '/groups/$groupId_/settings/account': typeof GroupsGroupIdSettingsAccountRoute
  '/groups/$groupId_/settings/group': typeof GroupsGroupIdSettingsGroupRoute
  '/groups/$groupId_/settings/members': typeof GroupsGroupIdSettingsMembersRoute
  '/groups/$groupId_/settings/': typeof GroupsGroupIdSettingsIndexRoute
  '/groups/$groupId_/courses_/$courseId_/lessons/$lessonId': typeof GroupsGroupIdCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ui'
    | '/groups/$groupId'
    | '/invite/$token'
    | '/overview/$lessonSlug'
    | '/groups/$groupId/courses'
    | '/groups/$groupId/members'
    | '/groups/$groupId/notifications'
    | '/groups/$groupId/words'
    | '/groups/$groupId/courses/$courseId'
    | '/groups/$groupId/members/$userId'
    | '/groups/$groupId/posts/$postId'
    | '/groups/$groupId/settings/account'
    | '/groups/$groupId/settings/group'
    | '/groups/$groupId/settings/members'
    | '/groups/$groupId/settings/'
    | '/groups/$groupId/courses/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ui'
    | '/groups/$groupId'
    | '/invite/$token'
    | '/overview/$lessonSlug'
    | '/groups/$groupId/courses'
    | '/groups/$groupId/members'
    | '/groups/$groupId/notifications'
    | '/groups/$groupId/words'
    | '/groups/$groupId/courses/$courseId'
    | '/groups/$groupId/members/$userId'
    | '/groups/$groupId/posts/$postId'
    | '/groups/$groupId/settings/account'
    | '/groups/$groupId/settings/group'
    | '/groups/$groupId/settings/members'
    | '/groups/$groupId/settings'
    | '/groups/$groupId/courses/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/ui'
    | '/groups/$groupId'
    | '/invite/$token'
    | '/overview/$lessonSlug'
    | '/groups/$groupId_/courses'
    | '/groups/$groupId_/members'
    | '/groups/$groupId_/notifications'
    | '/groups/$groupId_/words'
    | '/groups/$groupId_/courses_/$courseId'
    | '/groups/$groupId_/members_/$userId'
    | '/groups/$groupId_/posts/$postId'
    | '/groups/$groupId_/settings/account'
    | '/groups/$groupId_/settings/group'
    | '/groups/$groupId_/settings/members'
    | '/groups/$groupId_/settings/'
    | '/groups/$groupId_/courses_/$courseId_/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UiRoute: typeof UiRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OverviewLessonSlugRoute: typeof OverviewLessonSlugRoute
  GroupsGroupIdCoursesRoute: typeof GroupsGroupIdCoursesRoute
  GroupsGroupIdMembersRoute: typeof GroupsGroupIdMembersRoute
  GroupsGroupIdNotificationsRoute: typeof GroupsGroupIdNotificationsRoute
  GroupsGroupIdWordsRoute: typeof GroupsGroupIdWordsRoute
  GroupsGroupIdCoursesCourseIdRoute: typeof GroupsGroupIdCoursesCourseIdRoute
  GroupsGroupIdMembersUserIdRoute: typeof GroupsGroupIdMembersUserIdRoute
  GroupsGroupIdPostsPostIdRoute: typeof GroupsGroupIdPostsPostIdRoute
  GroupsGroupIdSettingsAccountRoute: typeof GroupsGroupIdSettingsAccountRoute
  GroupsGroupIdSettingsGroupRoute: typeof GroupsGroupIdSettingsGroupRoute
  GroupsGroupIdSettingsMembersRoute: typeof GroupsGroupIdSettingsMembersRoute
  GroupsGroupIdSettingsIndexRoute: typeof GroupsGroupIdSettingsIndexRoute
  GroupsGroupIdCoursesCourseIdLessonsLessonIdRoute: typeof GroupsGroupIdCoursesCourseIdLessonsLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview/$lessonSlug': {
      id: '/overview/$lessonSlug'
      path: '/overview/$lessonSlug'
      fullPath: '/overview/$lessonSlug'
      preLoaderRoute: typeof OverviewLessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/courses': {
      id: '/groups/$groupId_/courses'
      path: '/groups/$groupId/courses'
      fullPath: '/groups/$groupId/courses'
      preLoaderRoute: typeof GroupsGroupIdCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/members': {
      id: '/groups/$groupId_/members'
      path: '/groups/$groupId/members'
      fullPath: '/groups/$groupId/members'
      preLoaderRoute: typeof GroupsGroupIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/notifications': {
      id: '/groups/$groupId_/notifications'
      path: '/groups/$groupId/notifications'
      fullPath: '/groups/$groupId/notifications'
      preLoaderRoute: typeof GroupsGroupIdNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/words': {
      id: '/groups/$groupId_/words'
      path: '/groups/$groupId/words'
      fullPath: '/groups/$groupId/words'
      preLoaderRoute: typeof GroupsGroupIdWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/courses_/$courseId': {
      id: '/groups/$groupId_/courses_/$courseId'
      path: '/groups/$groupId/courses/$courseId'
      fullPath: '/groups/$groupId/courses/$courseId'
      preLoaderRoute: typeof GroupsGroupIdCoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/members_/$userId': {
      id: '/groups/$groupId_/members_/$userId'
      path: '/groups/$groupId/members/$userId'
      fullPath: '/groups/$groupId/members/$userId'
      preLoaderRoute: typeof GroupsGroupIdMembersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/posts/$postId': {
      id: '/groups/$groupId_/posts/$postId'
      path: '/groups/$groupId/posts/$postId'
      fullPath: '/groups/$groupId/posts/$postId'
      preLoaderRoute: typeof GroupsGroupIdPostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/settings/': {
      id: '/groups/$groupId_/settings/'
      path: '/groups/$groupId/settings'
      fullPath: '/groups/$groupId/settings/'
      preLoaderRoute: typeof GroupsGroupIdSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/settings/account': {
      id: '/groups/$groupId_/settings/account'
      path: '/groups/$groupId/settings/account'
      fullPath: '/groups/$groupId/settings/account'
      preLoaderRoute: typeof GroupsGroupIdSettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/settings/group': {
      id: '/groups/$groupId_/settings/group'
      path: '/groups/$groupId/settings/group'
      fullPath: '/groups/$groupId/settings/group'
      preLoaderRoute: typeof GroupsGroupIdSettingsGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/settings/members': {
      id: '/groups/$groupId_/settings/members'
      path: '/groups/$groupId/settings/members'
      fullPath: '/groups/$groupId/settings/members'
      preLoaderRoute: typeof GroupsGroupIdSettingsMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/courses_/$courseId_/lessons/$lessonId': {
      id: '/groups/$groupId_/courses_/$courseId_/lessons/$lessonId'
      path: '/groups/$groupId/courses/$courseId/lessons/$lessonId'
      fullPath: '/groups/$groupId/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof GroupsGroupIdCoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UiRoute: UiRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  OverviewLessonSlugRoute: OverviewLessonSlugRoute,
  GroupsGroupIdCoursesRoute: GroupsGroupIdCoursesRoute,
  GroupsGroupIdMembersRoute: GroupsGroupIdMembersRoute,
  GroupsGroupIdNotificationsRoute: GroupsGroupIdNotificationsRoute,
  GroupsGroupIdWordsRoute: GroupsGroupIdWordsRoute,
  GroupsGroupIdCoursesCourseIdRoute: GroupsGroupIdCoursesCourseIdRoute,
  GroupsGroupIdMembersUserIdRoute: GroupsGroupIdMembersUserIdRoute,
  GroupsGroupIdPostsPostIdRoute: GroupsGroupIdPostsPostIdRoute,
  GroupsGroupIdSettingsAccountRoute: GroupsGroupIdSettingsAccountRoute,
  GroupsGroupIdSettingsGroupRoute: GroupsGroupIdSettingsGroupRoute,
  GroupsGroupIdSettingsMembersRoute: GroupsGroupIdSettingsMembersRoute,
  GroupsGroupIdSettingsIndexRoute: GroupsGroupIdSettingsIndexRoute,
  GroupsGroupIdCoursesCourseIdLessonsLessonIdRoute:
    GroupsGroupIdCoursesCourseIdLessonsLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
